name = config['name']
query = config['query']
reference = config['reference']


rule rulename1:
     input:
        "hello.txt"

rule target1:
     output:
        "hello.txt"
     shell:
        "echo hello {name} > {output}"

rule target2:
     output:
        "goodbye.txt"
     shell:
        "echo goodbye {name} > {output}"

rule target3:
    output:
        "aln.txt"
    shell:
        '''
        echo aln {query} to {reference} > {output}
        '''